#include<stdio.h>
#include<conio.h>
int main()
{
clrscr();
printf("ans 1:%d\n",42+(30+47-20));
printf("ans 2:%d\n",77+43*9-61);
printf("ans 3:%d\n",(26-1)*2+100);
printf("ans 4:%d\n",(65+18-14)*7);
printf("ans 5:%d\n",76+26+70*1);
printf("ans 6:%d\n",42+(57+21)*3);
printf("ans 7:%d\n",40-(71*4)/6);
printf("ans 8:%d\n",83+(64/2)*10);
printf("ans 9:%d\n",(1*2)+92-53);
printf("ans 10:%d\n",(98+58-86)-84);
return 0;

}